# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"device": "03_auto_augment.ipynb",
         "ctrhw2tlbr": "00_vision_core.ipynb",
         "tlbr2cthw": "00_vision_core.ipynb",
         "activ_decode": "00_vision_core.ipynb",
         "activ_encode": "00_vision_core.ipynb",
         "strip_zero_rows": "00_vision_core.ipynb",
         "graft_zerorows_to_tensor": "00_vision_core.ipynb",
         "flip_on_y_axis": "00_vision_core.ipynb",
         "flip_on_x_axis": "00_vision_core.ipynb",
         "rotate_90_plus": "00_vision_core.ipynb",
         "rotate_90_minus": "00_vision_core.ipynb",
         "get_anchors": "01_anchor_boxes.ipynb",
         "show_anchors": "01_anchor_boxes.ipynb",
         "pad_output": "02_inference.ipynb",
         "get_activ_offsets_mns": "02_inference.ipynb",
         "fastai2pil_basis": "03_auto_augment.ipynb",
         "pil2fastai_basis": "03_auto_augment.ipynb",
         "pil2tensor": "03_auto_augment.ipynb",
         "flip_horizontal": "03_auto_augment.ipynb",
         "flip_vertical": "03_auto_augment.ipynb",
         "swap_xy_coords": "03_auto_augment.ipynb",
         "rotate_bb": "03_auto_augment.ipynb",
         "shear_x_bboxes": "03_auto_augment.ipynb",
         "rotate_bboxes": "03_auto_augment.ipynb",
         "ImageNetPolicy": "03_auto_augment.ipynb",
         "SubPolicy": "03_auto_augment.ipynb"}

modules = ["vision_core.py",
           "anchor_boxes.py",
           "inference.py",
           "auto_augment.py"]

doc_url = "https://jav0927.github.io/nextai_lib/"

git_url = "https://github.com/jav0927/nextai_lib/tree/main/"

def custom_doc_links(name): return None
