# AUTOGENERATED! DO NOT EDIT! File to edit: 03_auto_augment.ipynb (unless otherwise specified).

__all__ = ['device']

# Cell
from torch import tensor, Tensor
import torch

# Cell
# Automatically sets for GPU or CPU environments
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')